### ISSUE TITLE
Login Route not working

### ISSUE THREAD

**Issue by cziem** [phavor/yelpkamp#1]
The login route does not work from the `index.js` file from within the `controllers` directory...

But it works from the `routes.js` file.

Why is this behavior occurring?

**Comment by peoray** [comment]
Try this instead: 
```
 login: passport.authenticate('local', {
      successRedirect: '/campgrounds',
      failureRedirect: '/login'
    })
}
```

**Comment by cziem** [comment]
So I should get rid of the (req, res) huh?
